version: '3.3'

services:
  postgresql:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    env_file: ../.env

  app:
    container_name: rockety
    build:
      context: ./
    ports:
      - 80:8000
    volumes:
      - ../:/app
    env_file: ../.env
    depends_on:
      - postgresql